### ISSUE TITLE
Set up repository for and install Automated Regression Testing system components

### ISSUE THREAD

**Issue by CodeByDrescher** [virtualcell/vcell#248]
Once we have a stable VCell with an expanded math testing framework, we can build the remaining infrastructure to set up the Automated Regression Testing system.

**Comment by ACowan0105** [comment]
@CodeByDrescher @moraru I think this duplicates issue #185.  Can someone check and get rid of one or the other?  Perhaps 185 should be removed since Cory will be doing this and he will understand this one better.  Note that many of us biologists assume regression testing means directly comparing sim results, not just making sure a model is able to be saved and a simulation run so for clarity of the group it is better to identify exactly what this entails.  Trying to avoid repeating a long discussion at the meeting.

**Comment by CodeByDrescher** [comment]
Issue #185 was accidentally associated with the Automated regression testing milestone, when it was really a part of the Automated test suite milestone (this was corrected). Ion knows the specifics better than I, but the automated teste suite attempts to meticulously test VCell alongside other important features (for example, testing solver results from simulations with exact solutions). This issue was requested at the meeting in order to track the last task before completion of the Automated regression testing milestone.

**Comment by lesloew** [comment]
Completed; GitHub testing, Python batch script, and enhanced math testing have been set up
