### ISSUE TITLE
Setting BC bug

### ISSUE THREAD

**Issue by lesloew** [virtualcell/vcell#570]
In the model “FRAP_Membrane_testAlpha” (which I already shared with VCellSupport regarding Issue #566), I created a 2D Application called “Smaller 2D 100um, Value BC”. I tried to set all the BCs to “Value” and can save it with them set. However, when I reopen the model, it comes with several of the BCs set to Flux, which actually generates an error.

**Comment by moraru** [comment]
This is because default BC is flux and membrane BC is never saved (written/read to/from VCML/database) and if values is needed it will produce the error that needs to be fixed by the user every time the model is opened fresh.

The reason it is never saved is that membrane BC are almost always pre-determined by the enclosing volume BC, and actually not editable.  This is in fact properly checked for and enforced in the GUI.

However, the setting should always be saved, since there are very rare situations where it is not predetermined and it needs to be retrieved, and when it is predetermined it is already both correct and overridden by the checking algorithm.

**Comment by moraru** [comment]
Fixed in f21ffbf9e471d31baad6e9d983858af8018531f3

**Comment by moraru** [comment]
Fix is included in my draft PR (#567) with a big batch of other fixes and will become available once that PR is finalized and merged into master.

**Comment by danv61** [comment]
Additional fix, the database side of things.
Fixed in 5e62122
