### ISSUE TITLE
Non-equivalent math for particle stochastic applications

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#702]
Some models that have particle stochastic applications have newly generated math not equivalent with the original generated math.  The difference is in JumpProcess expressions, and almost always by a scaling factor.

**Comment by moraru** [comment]
Examples:
biomodel_83651737
biomodel_97075423
biomodel_97705317
biomodel_97786619
biomodel_97786886
biomodel_97787114
biomodel_98730962

One has a null symmetry factor, all others have a scaling factor in rate, either 2, KMOLE, or 10/KMOLE.

**Comment by moraru** [comment]
It is unclear whether the old or the new math are wrong.

**Comment by jcschaff** [comment]
debugging:

//
// create table with hybrid math descriptions
//
create table MATH_HYBRID as (select *
                             from VC_MATH
                             where dbms_lob.instr(LANGUAGE, 'ParticleJumpProcess') >= 1
                               and dbms_lob.instr(LANGUAGE, 'PdeEquation') >= 1);

//
// get biomodels/applications 
//
select VC_USERINFO.USERID,
       VC_BIOMODEL.VERSIONDATE as saved,
       vc_biomodel.id          as bmid,
       VC_BIOMODEL.NAME        as bmname,
       VC_SIMCONTEXT.NAME      as scname
from vc_biomodel
         join VC_BIOMODELSIMCONTEXT on VC_BIOMODELSIMCONTEXT.BIOMODELREF = VC_BIOMODEL.id
         join VC_SIMCONTEXT on VC_BIOMODELSIMCONTEXT.SIMCONTEXTREF = VC_SIMCONTEXT.ID
         join MATH_HYBRID on VC_SIMCONTEXT.MathRef = MATH_HYBRID.id
         join VC_USERINFO on VC_BIOMODEL.OWNERREF = VC_USERINFO.ID;

**Comment by jcschaff** [comment]
to get just the biomodel id's to download the VCML files:
```
select vc_biomodel.id          as bmid
from vc_biomodel
         join VC_BIOMODELSIMCONTEXT on VC_BIOMODELSIMCONTEXT.BIOMODELREF = VC_BIOMODEL.id
         join VC_SIMCONTEXT on VC_BIOMODELSIMCONTEXT.SIMCONTEXTREF = VC_SIMCONTEXT.ID
         join MATH_HYBRID on VC_SIMCONTEXT.MathRef = MATH_HYBRID.id;
```

**Comment by jcschaff** [comment]
Review of relevant commits to understand history and timeline of Hybrid Particle/PDE math generation:

- 10/6/2017 0d4fdca "ignore reactions without any stochasticity in ParticleMathMapping."
    - doesn't put in create/destroy actions for 'forced-continuous' species
    - doesn't add 'empty' ParticleJumpProcess (with no actions).
    - ParticleMathMapping
    - should account for MathDifferent_DIFFERENT_NUMBER_OF_PARTICLE_JUMP_PROCESS 
- 3/3/2017 8c22602 "Bug 5024 - patch Bug 4832 - Particle Hybrid math generation used wrong unit factors for continuous species." (patched fix)
    - ParticleMathMapping
    - should account for MathDifferent_DIFFERENT_PARTICLE_JUMP_PROCESS
    - There are two unit conversions required:
        - convert entire reaction rate from vcell reaction units to Smoldyn units (molecules/lengthunit^dim/timeunit)
        - convert each reactant/product from Smoldyn units (molecules/lengthunit^dim) to VCell units
- 8/22/2016 3962a37 "Bug 4832 - Particle Hybrid math generation used wrong unit factors for continuous species." (original fix)
    - same as above - should account for MathDifferent_DIFFERENT_PARTICLE_JUMP_PROCESS
- 3/30/2016 67e5d07 "Bug 4674 - stochastic math generation scales reaction propensities with wrong compartment size."
    - computed species substances used in rate by always diving by size of  unit factor based on Reaction structure size, not species structure size
    - StochMathMapping this is for non-spatial only
- 12/14/2015 f8e11e9ec "Bug 4559 - fixed math generation for fluxes in nonspatial stochastic applications"
    - effects Probability Rate units of Flux Reactions
    - StochMathMapping this is for non-spatial only
- 8/8/2015 9a2541a080 "Bug 4387 : adding reversible to reactionSteps (simpleReactions and fluxes) - refactoring and reconciling Rules and nonspatial stochastic math generation."
    - StochMathMapping RulebasedMathMapping AbstractStochMathMapping reconcile NFSim/SSA
- 8/5/2015 d6f28950e1b "Bug 4385 - careful symbol and unit handling in stochastic math generation".
    - looks like bookkeeping, but no bug fixes or changes
- 1/23/2015 36509854a "Bug 4073 : Inhibit variable elimination due to mass conserv. for hybrid reactions and particles"
    - ParticleMathMapping - not sure if this would change math or prevent mathgen failures?
- 6/18/2013 5c5ada97a69 "Bug 3551 : BioModel support for hybrid particle-pde solver"
    - Initial commit for Hybrid Particle/PDEs.

**Comment by jcschaff** [comment]
finally - impact on legacy hybrid Particle/PDE applications:

- 9 private Biomodels (13 hybrid Particle/PDE applications) had a probability rate scaled by scaled by KMOLE (602)
   - These models were saved between June 2013 and July 2015 by 3 different external users.
   - These users will be informed this week.
- 2 public model versions with rate scaled by 2.0 
   - Two versions of the same model (Mix_Reactions_Rules) were saved by user BioNetGen (@vcellmike) in Nov 2015.
   - these models will be resaved and rerun.
