### ISSUE TITLE
GUI scaling linux

### ISSUE THREAD

**Issue by pcarlip** [virtualcell/vcell#845]
After running the 64-bit Linux installer, the VCell-Rel program doesn't scale to my high dpi screen, leaving the text, buttons, etc. too small to easily interact with.
![Screenshot_20230330_121731](https://user-images.githubusercontent.com/42861501/228900367-6088efad-a426-41c1-88a2-40c7258b6170.png)

**Comment by CodeByDrescher** [comment]
Hello Mr. Carlip (@pcarlip), 

I looked into this and was able to replicate the issue. However, this project still has some dependencies that require Java 1.8, and while we are working on upgrading to the latest Java version, this issue appears to be unfortunately blocked.

**Comment by CodeByDrescher** [comment]
Blocked by #848

**Comment by CodeByDrescher** [comment]
Issue #848 has been solved and pushed to VCell's Alpha version; this issue is seemingly fixed. There may be a few visual bugs still, but the scaling should be fine. Down the line this will move to Release, but for now @pcarlip please use the Alpha client for Linux found here: https://vcell.org/webstart/Alpha/VCell_Alpha_unix_latest_64bit.sh
